[package]
name = "libsignal-net-infra"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
test-util = ["dep:warp", "snow/default-resolver"]
dev-util = []

[dependencies]
attest = { workspace = true }

async-trait = { workspace = true }
auto_enums = { version = "0.8.7", features = ["tokio1"] }
base64 = { workspace = true }
bitstream-io = "1.10.0"
boring-signal = { workspace = true }
bytes = "1.4.0"
const-str = { workspace = true, features = ["std"] }
derive-where = { workspace = true }
derive_more = { workspace = true, features = ["from", "into", "into_iterator"] }
displaydoc = { workspace = true }
either = "1.10.0"
futures-util = { workspace = true }
http = { workspace = true }
http-body-util = "0.1.1"
hyper = { version = "1.3.1", features = ["http1", "http2", "client"] }
hyper-util = { version = "0.1.3", features = ["tokio"] }
indexmap = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
nonzero_ext = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
rangemap = "1.5.1"
rustls = { version = "0.23.4", default-features = false, features = ["ring", "std", "tls12"] }
rustls-platform-verifier = { workspace = true }
snow = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "macros"] }
tokio-boring-signal = { workspace = true }
tokio-socks = "0.5.2"
tokio-stream = { workspace = true }
tokio-tungstenite = "0.23.0"
tokio-util = "0.7.9"
tungstenite = { version = "0.23.0", features = ["url"] }
url = "2.4.1"
visibility = { workspace = true }
warp = { version = "0.3.6", features = ["tls"], optional = true }

[dev-dependencies]
assert_matches = { workspace = true }
env_logger = { workspace = true }
hickory-proto = "0.24.1"
hyper = { version = "1.3.1", features = ["http1", "server"] }
lazy_static = { workspace = true }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
rcgen = "0.13.0"
snow = { workspace = true, features = ["default-resolver"] }
socks5-server = "0.10.1"
test-case = { workspace = true }
test-log = { workspace = true }
tls-parser = "0.12.2"
tokio = { workspace = true, features = ["test-util", "io-std", "rt-multi-thread"] }
warp = { version = "0.3.6", features = ["tls"] }
