name: Docs

env:
  MDBOOK_VERSION: "0.4.43"

on:
  push:
    branches: [ main ]
    paths: ['doc/**', '.github/workflows/docs.yml']
  pull_request:
    paths: ['doc/**', '.github/workflows/docs.yml']

jobs:
  docs:
    name: Check docs

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: recursive

    - name: Download mdbook ${{ env.MDBOOK_VERSION }}
      run: mkdir ~/bin && curl -sSL https://github.com/rust-lang/mdBook/releases/download/v${{ env.MDBOOK_VERSION }}/mdbook-v${{ env.MDBOOK_VERSION }}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory ~/bin

    - run: ~/bin/mdbook build
      working-directory: doc

    - run: ~/bin/mdbook test
      working-directory: doc
